settings:
  application:
    mode: dev  # dev开发环境 test测试环境 prod线上环境
    host: 0.0.0.0
    name: gin-admin-backend
    port: 8080
    readtimeout: 1
    writertimeout: 2
    domain: localhost:8000
    ishttps: false
    pagesize: 10
  ssl:
    key: keystring
    pem: temp/pem.pem
  log:
    operdb: false
    dir: logs
  jwt:
    secret: go-admin
    timeout: 3600
  database:
    name: goadmin
    dbtype: mysql
    host: 127.0.0.1
    password: 152258
    port: 9000
    username: root
